# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qZpbzBi9yZyFO6U_wF54SH0hVNH_wB3x
"""

print("hello world")